import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { defineCommand } from 'citty';
import { ConfigError, loadOvellumConfig } from '@ovellum/core';

/**
 * `ovellum agents` — keep a canonical "## Ovellum docs" section in the
 * project's top-level agent-instruction files (`AGENTS.md` / `CLAUDE.md`).
 *
 * The section tells a coding agent how docs work here (mode, what's
 * regenerated, the protected-zone contract, which commands to run) and where
 * to learn more. The command is idempotent and surgical: it adds the section
 * if missing, replaces it if stale, touches nothing else in the file, and
 * writes nothing at all when the section is already current. If neither file
 * exists it creates `AGENTS.md` containing only the section.
 */

/** The heading that identifies the canonical section. */
export const OVELLUM_DOCS_HEADING = '## Ovellum docs';

const AUTOMATION_URL = 'https://ovellum.oss.oinam.com/docs/guides/automation/';

export interface AgentsSectionOptions {
  mode: 'manual' | 'auto' | 'hybrid';
  input: string;
  output: string;
  orphanDir?: string;
}

/**
 * Render the canonical section. Mode-aware, like `renderAgentsMd`: hybrid and
 * auto lead with what gets regenerated (the rule an agent most needs), manual
 * with "edit the Markdown, never the output". Deterministic for a given
 * config, so the upsert can detect "already current" by comparing content.
 */
export function renderOvellumDocsSection(o: AgentsSectionOptions): string {
  const orphanDir = o.orphanDir ?? '.ovellum/orphans';

  if (o.mode === 'manual') {
    return `${OVELLUM_DOCS_HEADING}

Documentation in this repository is managed by [Ovellum](https://ovellum.oss.oinam.com)
in **manual** mode.

- Edit the Markdown under \`${o.input}/\`. The built site in \`${o.output}/\` is
  regenerated by \`ovellum build\` — never edit it by hand.
- Run \`ovellum check\` after doc edits — it validates internal links and exits
  \`1\` on issues (\`--json\` for machine output).
- The built site ships AI-readable mirrors (\`/llms.txt\` plus a \`.md\` twin per
  page), and \`ovellum mcp\` runs an MCP server (search, read, build).

More: ${AUTOMATION_URL}
`;
  }

  if (o.mode === 'auto') {
    return `${OVELLUM_DOCS_HEADING}

Documentation in this repository is managed by [Ovellum](https://ovellum.oss.oinam.com)
in **auto** mode: fully generated from TypeScript/JavaScript source.

- \`${o.output}/\` is regenerated on every \`ovellum build\` — never edit it by
  hand; change the JSDoc/TSDoc in the source instead.
- \`ovellum diff\` previews what a rebuild would change; \`ovellum check\`
  validates links and exits \`1\` on issues (\`--json\` for machine output).
- \`ovellum mcp\` runs an MCP server so agents can query symbols, diff, search,
  and build.

More: ${AUTOMATION_URL}
`;
  }

  return `${OVELLUM_DOCS_HEADING}

Documentation in this repository is managed by [Ovellum](https://ovellum.oss.oinam.com)
in **hybrid** mode: generated from source, merged with hand-written prose.

- \`${o.output}/\` is regenerated on every \`ovellum build\`. Hand-written prose
  survives **only** inside \`<!-- @manual:start id="…" --> … <!-- @manual:end -->\`
  zones; everything outside is overwritten. To change generated content, edit
  the JSDoc/TSDoc in the source.
- Prose whose symbol disappeared is quarantined to \`${orphanDir}/\`, never
  dropped — review with \`ovellum orphans\`; preview drift with \`ovellum diff\`.
- \`ovellum check\` validates links and anchors and exits \`1\` on issues
  (\`--json\` for machine output). \`ovellum mcp\` runs an MCP server whose
  \`ovellum_write_zone\` tool writes prose into a protected zone safely.

More: ${AUTOMATION_URL}
`;
}

/** Locate the canonical section: from its heading to the next h1/h2 (or EOF). */
function findSection(lines: string[]): { start: number; end: number } | null {
  let start = -1;
  for (let i = 0; i < lines.length; i++) {
    if ((lines[i] ?? '').trim() === OVELLUM_DOCS_HEADING) {
      start = i;
      break;
    }
  }
  if (start === -1) return null;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^#{1,2}\s/.test(lines[i] ?? '')) {
      end = i;
      break;
    }
  }
  return { start, end };
}

export interface UpsertResult {
  content: string;
  /** false when the existing section already matches — nothing to write. */
  changed: boolean;
  /** whether a section heading was found at all. */
  found: boolean;
}

/**
 * Replace the existing "## Ovellum docs" section, or append one at the end.
 * Everything outside the section is preserved verbatim; when the section is
 * already current the input is returned untouched (`changed: false`), so a
 * repeat run never makes a formatting-only write.
 */
export function upsertOvellumDocsSection(raw: string, section: string): UpsertResult {
  const sec = section.trimEnd() + '\n';
  const lines = raw.split('\n');
  const loc = findSection(lines);

  if (loc === null) {
    const base = raw.replace(/\s+$/, '');
    const content = base.length > 0 ? `${base}\n\n${sec}` : sec;
    return { content, changed: true, found: false };
  }

  const existing = lines.slice(loc.start, loc.end).join('\n');
  if (existing.trim() === sec.trim()) {
    return { content: raw, changed: false, found: true };
  }

  const before = lines.slice(0, loc.start).join('\n').replace(/\s+$/, '');
  const after = lines.slice(loc.end).join('\n').replace(/^\n+/, '');
  const content = (before.length > 0 ? `${before}\n\n` : '') + sec + (after.length > 0 ? `\n${after}` : '');
  return { content, changed: true, found: true };
}

export interface AgentsFileResult {
  file: string;
  action: 'created' | 'updated' | 'current' | 'missing' | 'stale';
}

/**
 * Apply (or, with `check`, only verify) the section across the project's
 * top-level `AGENTS.md` and `CLAUDE.md`. Whichever of the two exists is
 * updated — both when both exist. When neither does, `AGENTS.md` is created
 * with just the section.
 */
export async function syncAgentsFiles(
  cwd: string,
  section: string,
  check: boolean,
): Promise<AgentsFileResult[]> {
  const targets = ['AGENTS.md', 'CLAUDE.md'].filter((f) => existsSync(path.join(cwd, f)));

  if (targets.length === 0) {
    if (check) return [{ file: 'AGENTS.md', action: 'missing' }];
    await writeFile(path.join(cwd, 'AGENTS.md'), section.trimEnd() + '\n', 'utf8');
    return [{ file: 'AGENTS.md', action: 'created' }];
  }

  const results: AgentsFileResult[] = [];
  for (const file of targets) {
    const abs = path.join(cwd, file);
    const raw = await readFile(abs, 'utf8');
    const { content, changed, found } = upsertOvellumDocsSection(raw, section);
    if (!changed) {
      results.push({ file, action: 'current' });
    } else if (check) {
      results.push({ file, action: found ? 'stale' : 'missing' });
    } else {
      await writeFile(abs, content, 'utf8');
      results.push({ file, action: 'updated' });
    }
  }
  return results;
}

const ACTION_LABELS: Record<AgentsFileResult['action'], string> = {
  created: 'created (with the Ovellum docs section)',
  updated: 'Ovellum docs section updated',
  current: 'already current',
  missing: 'MISSING the Ovellum docs section',
  stale: 'Ovellum docs section is STALE',
};

export const agentsCommand = defineCommand({
  meta: {
    name: 'agents',
    description:
      'Add or refresh the canonical "Ovellum docs" section in AGENTS.md / CLAUDE.md (idempotent).',
  },
  args: {
    config: {
      type: 'string',
      description: 'Path to ovellum.config.{ts,js,json} (auto-discovered otherwise).',
    },
    cwd: { type: 'string', description: 'Project root (defaults to the current directory).' },
    check: {
      type: 'boolean',
      default: false,
      description: 'Verify only — exit 1 if the section is missing or stale, write nothing.',
    },
  },
  async run({ args }) {
    const cwd = path.resolve(args.cwd ?? process.cwd());
    let loaded;
    try {
      loaded = await loadOvellumConfig({ cwd, configFile: args.config });
    } catch (err) {
      if (err instanceof ConfigError) {
        process.stderr.write(`config error: ${err.message}\n`);
        if (err.hint) process.stderr.write(`hint: ${err.hint}\n`);
        process.exit(3);
      }
      throw err;
    }
    const { config } = loaded;

    const section = renderOvellumDocsSection({
      mode: config.mode,
      input: config.input,
      output: config.output,
      orphanDir: config.protect.orphanDir,
    });
    const results = await syncAgentsFiles(cwd, section, args.check === true);

    process.stdout.write(`ovellum agents${args.check ? ' --check' : ''}:\n`);
    for (const r of results) {
      process.stdout.write(`  ${r.file}  ${ACTION_LABELS[r.action]}\n`);
    }

    if (args.check && results.some((r) => r.action === 'missing' || r.action === 'stale')) {
      process.stdout.write('\nRun `ovellum agents` to write the section.\n');
      process.exit(1);
    }
  },
});
